version: '3'
services:
  web:
    build: .
    ports:
      - "4000:80"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/students.db

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "flask_user"
      POSTGRES_PASSWORD: "flask_password"
      POSTGRES_DB: "flask_db"